version: '3.8'

services:
  frontend:
    image: python:3.9-slim
    container_name: frontend_container
    working_dir: /app
    volumes:
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt 
    command: sh -c "pip install -r requirements.txt && python app.py"
    networks:
      - frontend-backend-net

networks:
  frontend-backend-net:
    external: true
