version: '3.8'

services:
  adminer:
    image: adminer
    container_name: adminer-postgrew
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
